// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReacodeApp.Data;

#nullable disable

namespace ReacodeApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109124139_AddCartModel")]
    partial class AddCartModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReacodeApp.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ReacodeApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9256),
                            Description = "Fresh vegetables",
                            IsActive = true,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9260),
                            Description = "Fresh fruits",
                            IsActive = true,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9262),
                            Description = "Cereals and grains",
                            IsActive = true,
                            Name = "Grains"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9263),
                            Description = "Fresh herbs and spices",
                            IsActive = true,
                            Name = "Herbs"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9265),
                            Description = "Dairy products",
                            IsActive = true,
                            Name = "Dairy"
                        });
                });

            modelBuilder.Entity("ReacodeApp.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ReacodeApp.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ReacodeApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryCity")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryNotes")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryProvince")
                        .HasColumnType("text");

                    b.Property<int>("FarmerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ReacodeApp.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ReacodeApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 50,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9603),
                            Description = "Premium organic tomatoes grown in our greenhouse. Perfect for salads, cooking, and fresh eating.",
                            ExpiryDate = new DateTime(2025, 11, 14, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9602),
                            FarmerId = 10,
                            HarvestDate = new DateTime(2025, 11, 7, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9597),
                            ImageUrl = "https://images.unsplash.com/photo-1546470427-5bb7c3a1b7b8?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Cape Town, Western Cape",
                            Name = "Fresh Organic Tomatoes",
                            PricePerKg = 45.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9604)
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 30,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9610),
                            Description = "Fresh sweet corn harvested daily. Great for grilling, boiling, or adding to salads.",
                            ExpiryDate = new DateTime(2025, 11, 16, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9608),
                            FarmerId = 10,
                            HarvestDate = new DateTime(2025, 11, 8, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9608),
                            ImageUrl = "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Cape Town, Western Cape",
                            Name = "Sweet Corn",
                            PricePerKg = 35.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9610)
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 25,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9614),
                            Description = "Sweet, juicy strawberries perfect for desserts, smoothies, or eating fresh.",
                            ExpiryDate = new DateTime(2025, 11, 12, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9614),
                            FarmerId = 11,
                            HarvestDate = new DateTime(2025, 11, 8, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9613),
                            ImageUrl = "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Johannesburg, Gauteng",
                            Name = "Fresh Strawberries",
                            PricePerKg = 80.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9615)
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 40,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9619),
                            Description = "Crisp, sweet organic apples from our orchard. Perfect for snacking or baking.",
                            ExpiryDate = new DateTime(2025, 11, 23, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9618),
                            FarmerId = 11,
                            HarvestDate = new DateTime(2025, 11, 6, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9618),
                            ImageUrl = "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Johannesburg, Gauteng",
                            Name = "Organic Apples",
                            PricePerKg = 55.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9620)
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9624),
                            Description = "Aromatic fresh basil perfect for Italian dishes, pesto, and garnishing.",
                            ExpiryDate = new DateTime(2025, 11, 14, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9623),
                            FarmerId = 12,
                            HarvestDate = new DateTime(2025, 11, 8, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9622),
                            ImageUrl = "https://images.unsplash.com/photo-1615485925442-7b4b8b5b5b5b?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Durban, KwaZulu-Natal",
                            Name = "Fresh Basil",
                            PricePerKg = 120.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9624)
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9629),
                            Description = "Fragrant rosemary perfect for roasting, grilling, and Mediterranean dishes.",
                            ExpiryDate = new DateTime(2025, 11, 16, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9628),
                            FarmerId = 12,
                            HarvestDate = new DateTime(2025, 11, 7, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9627),
                            ImageUrl = "https://images.unsplash.com/photo-1615485925442-7b4b8b5b5b5b?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Durban, KwaZulu-Natal",
                            Name = "Fresh Rosemary",
                            PricePerKg = 100.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9629)
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 35,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9634),
                            Description = "Premium organic quinoa, high in protein and perfect for healthy meals.",
                            ExpiryDate = new DateTime(2026, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9633),
                            FarmerId = 10,
                            HarvestDate = new DateTime(2025, 11, 4, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9632),
                            ImageUrl = "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Cape Town, Western Cape",
                            Name = "Organic Quinoa",
                            PricePerKg = 95.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9634)
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 60,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9638),
                            Description = "Sweet, crunchy carrots perfect for snacking, cooking, or juicing.",
                            ExpiryDate = new DateTime(2025, 11, 19, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9637),
                            FarmerId = 11,
                            HarvestDate = new DateTime(2025, 11, 7, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9637),
                            ImageUrl = "https://images.unsplash.com/photo-1598170845058-32b9d6a5da35?w=400&h=300&fit=crop",
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Johannesburg, Gauteng",
                            Name = "Fresh Carrots",
                            PricePerKg = 25.00m,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9639)
                        });
                });

            modelBuilder.Entity("ReacodeApp.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("ReacodeApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Address = "123 Farm Road",
                            City = "Cape Town",
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9543),
                            Email = "farmer1@example.com",
                            FirstName = "John",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Smith",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            PhoneNumber = "+27 82 123 4567",
                            PostalCode = "8000",
                            Province = "Western Cape",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9544)
                        },
                        new
                        {
                            Id = 11,
                            Address = "456 Harvest Lane",
                            City = "Johannesburg",
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9551),
                            Email = "farmer2@example.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Johnson",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            PhoneNumber = "+27 83 987 6543",
                            PostalCode = "2000",
                            Province = "Gauteng",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9551)
                        },
                        new
                        {
                            Id = 12,
                            Address = "789 Green Valley",
                            City = "Durban",
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9555),
                            Email = "farmer3@example.com",
                            FirstName = "Mike",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Brown",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            PhoneNumber = "+27 84 555 1234",
                            PostalCode = "4000",
                            Province = "KwaZulu-Natal",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9556)
                        },
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9670),
                            Email = "admin@reacoda.com",
                            FirstName = "System",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Admin",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = 2,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9670)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9673),
                            Email = "superadmin@reacoda.com",
                            FirstName = "Super",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Admin",
                            PasswordHash = "40+SogUyqHPLMYQ5gHC0uCqPopz0hXLCA9xfD6YVgjE=",
                            Role = 3,
                            UpdatedAt = new DateTime(2025, 11, 9, 12, 41, 38, 504, DateTimeKind.Utc).AddTicks(9673)
                        });
                });

            modelBuilder.Entity("ReacodeApp.Models.Cart", b =>
                {
                    b.HasOne("ReacodeApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReacodeApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReacodeApp.Models.Favorite", b =>
                {
                    b.HasOne("ReacodeApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReacodeApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReacodeApp.Models.Notification", b =>
                {
                    b.HasOne("ReacodeApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReacodeApp.Models.Order", b =>
                {
                    b.HasOne("ReacodeApp.Models.User", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReacodeApp.Models.User", "Farmer")
                        .WithMany("OrdersReceived")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("ReacodeApp.Models.OrderItem", b =>
                {
                    b.HasOne("ReacodeApp.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReacodeApp.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReacodeApp.Models.Product", b =>
                {
                    b.HasOne("ReacodeApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReacodeApp.Models.User", "Farmer")
                        .WithMany("Products")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("ReacodeApp.Models.ProductReview", b =>
                {
                    b.HasOne("ReacodeApp.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReacodeApp.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ReacodeApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ReacodeApp.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ReacodeApp.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ReacodeApp.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("OrdersReceived");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
